config/routes.rb
Rails.application.routes.draw do

  resources :activities, only: [:index]

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login", to: "devise/sessions#new", as: :new_user_session
    post "/login", to: "devise/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
      put 'like', to: 'statuses#upvote'
      put 'dislike', to: 'statuses#downvote'
    end
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  scope ':nick_name' do
    resources :albums do
      resources :pictures
    end
  end

  resources :conversations do
    resources :messages
  end

  get '/:id', to: 'profiles#show', as: 'profile'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_nick_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render :file => 'public/404.html', :status => 404, format: [:html]
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="header col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
  <h1><%= @user.full_name %> | <%= link_to 'Galleries', albums_path(@user),class: 'btn btn-default' %></h1>


  <%if signed_in? %>
      <div id="friend-status">
        <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
            <%= link_to 'Edit Friendship', edit_user_friendship_path(friend_id: @user), class: 'btn btn-warning' %>
        <% else %>
            <% if current_user != @user %>
            <%= link_to 'Add to Friendzone', new_user_friendship_path(friend_id: @user), class: 'btn btn-primary',
                        id: 'add-friendship', data: { friend_id: @user.to_param } %>
                <% end %>
      <% end %>
      </div>
  <% end %>
  <div class="border_custom"></div>

  <% if @statuses %>
      <% @statuses.each do |status| %>
          <div class="profile_stats col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
            <%= status.content %>
          <hr>
          <%= link_to time_ago_in_words(status.created_at), status_path(status)%> ago
          </div>
      <%end%>
  <% else %>
      <div class="profile_stats col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
        <h3>You should start sending statuses or get out</h3>
      </div>
  <%end %>
</div>