config/routes.rb
Rails.application.routes.draw do

  resources :activities, only: [:index]

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login", to: "devise/sessions#new", as: :new_user_session
    post "/login", to: "devise/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
      put 'like', to: 'statuses#upvote'
      put 'dislike', to: 'statuses#downvote'
    end
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  scope ':nick_name' do
    resources :albums do
      resources :pictures
    end
  end

  resources :conversations do
    resources :messages
  end

  get '/:id', to: 'profiles#show', as: 'profile'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /statuses
  def index
    # @statuses = Status.order('updated_at DESC').all
    if params[:search]
      @statuses = Status.search(params[:search]).order('updated_at DESC')
    else
      @statuses = Status.all.order('updated_at DESC')
    end
  end

  # GET /statuses/1
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
    @status.build_document
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        current_user.create_activity(@status,'created')
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /statuses/1
  def update
    @status = current_user.statuses.find(params[:id])
    @document = @status.document

    @status.transaction do
      @status.update_attributes(params[:status])
      @document.update_attributes(params[:status][:document]) if @document
      current_user.create_activity(@status,'updated')
      unless @status.valid? || (@status.valid? && @document && !document.valid?)
        raise ActiveRecord::Rollback
      end
    end

    respond_to do |format|
      format.html { redirect_to @status, notice: 'Status was successfully updated.' }
    end

  rescue ActiveRecord::Rollback
      respond_to do |format|
        format.html do
          flash.now[:error] = 'Update failed'
          render :edit
        end
        format.html { render :edit }
    end
  end

  # DELETE /statuses/1
  def destroy
    @status.destroy
    current_user.create_activity(@status,'deleted')
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
    end
  end

  def upvote
    @status = Status.find(params[:id])
    @status.upvote_by current_user
    redirect_to root_path
  end

  def downvote
    @status = Status.find(params[:id])
    @status.downvote_by current_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id, :document_attributes => [:attachment])
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
    <%= simple_form_for @status, html: {class: 'form-horizontal', multipart: true} do |f| %>
      <% if @status.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

          <ul>
          <% @status.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :content %>
      <%= f.fields_for :document do |document_fields|%>
          <% if document_fields.object.attachment? %>
            <div class="control-group">
              <label for="" class="control-label">Current file</label>
              <div class="controls">
                <%= link_to document_fields.object.attachment_file_name,
                            document_fields.object.attachment.url %>
              </div>
            </div>
              <%= document_fields.input :remove_attachment, as: :boolean, label: 'Remove file?'%>
          <% end %>
        <%= document_fields.input :attachment, as: :file %>
      <% end %>

      <div class="actions">
        <%= f.button :submit, :class => 'btn-primary'%>
      </div>
    <% end %>
</div>

app/views/statuses/edit.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
<h1>Editing Status</h1>
</div>
<%= render 'form' %>

<div style="margin-top: 20px;" class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

  <%= link_to 'Show', @status, :class => 'btn btn-success' %> |
  <%= link_to 'Back', statuses_path, :class => 'btn btn-default' %>

</div>

app/views/statuses/index.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
    <h1>Statuses</h1>
    <div class="border_custom"></div>
    <div class="new-stat">
      <%= link_to 'New Status', new_status_path, {:class => 'btn btn-primary'}%>
    </div>
</div>
<% if @statuses.present? %>
    <% @statuses.each do |status| %>
        <% if can_display_status?(status) %>
            <div class="row wrapper-statuses" style="clear: left;">
                <div class="wrapper_gravatar col-sm-2 col-md-1 col-lg-1">
                  <%= avatar_profile_link status.user, {class:'img-circle', width: '100px', height: '100px'},class: 'high-test' %>
                </div>
                <div class="col-sm-8 col-lg-9 col-lg-9">
                    <div class="status">
                      <h3><%= status.user.full_name %>
                        <% if current_user != status.user %>
                        <span>
                          <%= link_to 'Send Message', '#', class: 'btn btn-success btn-xs start-conversation',
                                                                         'data-sid' => current_user.id, 'data-rip' => status.user.id %>
                        </span>
                            <% end %>
                      </h3>
                      <p><%= status.content %></p>
                      <%= show_file(status) %>
                      <div style="padding-bottom: 5px; padding-top: 5px;">
                        <span><%= link_to 'Like', like_status_path(status), method: :put %></span>
                        | <span><%= link_to 'Dislike', dislike_status_path(status), method: :put %></span> | <span><%= status.score %></span></div>
                      <div class="links-buttons">
                        <%= link_to time_ago_in_words(status.created_at) + ' ago', status %>
                        <% if signed_in? && current_user == status.user %>
                        <span class="admin">
                          | <%= link_to 'Edit', edit_status_path(status) %>
                          | <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure you want to delete? We own it.' } %>
                        </span>
                            <% end %>
                      </div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
<% else %>
    <div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
        <h3 class="label label-danger" style="font-size: 100%;">There are no statuses containing the term(s) <%= params[:search] %>.</h3>
    </div>
<% end %>

app/views/statuses/new.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
<h1>New Status</h1>
  <div class="border_custom"></div>
</div>

<%= render 'form' %>


  <div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12" style="margin-top: 15px;">
<%= link_to 'Back', statuses_path, class: 'btn btn-default' %>
  </div>

app/views/statuses/show.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>
  <% if @status.document && @status.document.attachment? %>
      <span class="label label-info">File</span>
      <%= link_to @status.document.attachment_file_name,
                  @status.document.attachment.url %>
  <% end %>
  <hr>
<%= link_to 'Edit', edit_status_path(@status), :class => 'btn btn-primary' %> |
<%= link_to 'Back', statuses_path, :class => 'btn btn-default' %>
</div>