config/routes.rb
Rails.application.routes.draw do

  resources :activities, only: [:index]

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login", to: "devise/sessions#new", as: :new_user_session
    post "/login", to: "devise/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
      put 'like', to: 'statuses#upvote'
      put 'dislike', to: 'statuses#downvote'
    end
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  scope ':nick_name' do
    resources :albums do
      resources :pictures
    end
  end

  resources :conversations do
    resources :messages
  end

  get '/:id', to: 'profiles#show', as: 'profile'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  belongs_to :user

  has_attached_file :asset, styles: {
                        large: '800x800>',
                        medium: '300x200>',
                        small: '260x180>',
                        thumb: '80x80#',
                          }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/

  def to_s
    caption ? caption : 'Picture'
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_user
  before_filter :find_album
  before_filter :add_breadcrumbs
  before_filter :ensure_proper_user, only: [:edit, :new, :create, :update, :destroy]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @album.pictures.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = @album.pictures.find(params[:id])
    add_breadcrumb @picture, album_picture_path(@album, @picture)
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @album.pictures.new(picture_params)
    @picture.user = current_user

    respond_to do |format|
      if @picture.save
        current_user.create_activity(@picture,'created')
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        current_user.create_activity(@picture,'updated')
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    current_user.create_activity(@picture,'deleted')
    respond_to do |format|
      format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def url_options
    { nick_name: params[:nick_name] }.merge(super)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:album_id, :user_id, :caption, :description, :asset)
    end

  def find_user
    @user = User.find_by_nick_name(params[:nick_name])
  end

  def find_album
    if signed_in? && current_user.nick_name == params[:nick_name]
      @album = current_user.albums.find(params[:album_id])
    else
      @album = @user.albums.find(params[:album_id])
    end
  end

  def find_picture
    @picture = @album.pictures.find(params[:picture_id])
  end

  def add_breadcrumbs
    add_breadcrumb @user.first_name, profile_path(@user)
    add_breadcrumb 'Galleries', albums_path
    add_breadcrumb 'Pictures', album_pictures_path(@album)
  end

  def ensure_proper_user
    if current_user != @user
      flash[:error] = 'You dont dave permissions'
      redirect_to album_pictures_path
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def can_edit_picture?(picture)
    signed_in? && current_user == picture.user
  end

  def paperclip_picture(form , paperclip_obj)
    if form.object.send("#{paperclip_obj}?")
      content_tag(:div, class: 'control-group') do
        content_tag(:label, "Curent #{paperclip_obj.to_s.titleize}", class: 'control-label')
        content_tag(:div, class: 'controls') do
          image_tag form.object.send(paperclip_obj).send(:url, :small)
        end
      end
    end
  end
end

app/views/pictures/_form.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

<%= simple_form_for([@album, @picture], html: { class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :asset, as: :file,label: 'Picture' %>
    <%= paperclip_picture f, :asset %>
    <%= f.input :caption %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>
</div>

app/views/pictures/edit.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

<h1>Edit</h1>

<%= render 'form' %>
</div>
<div style="margin-top: 20px;" class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

<%= link_to 'Show', album_picture_path(@album, @picture), class: 'btn btn-primary' %> |
<%= link_to 'Back', album_pictures_path(@album),class: 'btn btn-default' %>
</div>

app/views/pictures/index.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
  <% if signed_in? && current_user == @user %>
    <p><%= link_to 'Share new pic', new_album_picture_path(current_user, @album),class: 'btn btn-primary' %></p>
  <% end %>
  <h1><%= @album.title %></h1>
  <hr>
</div>
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

    <% @pictures.each do |picture| %>
      <div class="col-sm-4 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(picture.asset.url(:small)), album_picture_path(@user, @album, picture) %>
          <div class="caption" style="text-align: center">
            <% if picture.caption? %>
                <h4><%= picture.caption %></h4>
            <% end %>
            <% if picture.description? %>
                <p><%= picture.description %></p>
            <% end %>
            <p>
              <%=  link_to 'Full size', album_picture_path(@user, @album, picture), class: 'btn btn-success' %>
              <% if can_edit_picture?(picture) %>
                  |<%= link_to 'Edit', edit_album_picture_path(@album, picture), class: 'btn btn-warning' %>
                  |<%= link_to 'Delete', album_picture_path(@album, picture), method: :delete,
                              data: {confirm: 'are you sure?'}, class: 'btn btn-danger' %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/pictures/new.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">
<h1>New Picture</h1>
  <hr>
<%= render 'form' %>
</div>
<div style="margin-top: 20px;" class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

<%= link_to 'Back', album_pictures_path(@album), class: 'btn btn-default' %>
</div>

app/views/pictures/show.html.erb
<div class="col-lg-offset-1 col-lg-10 col-sm-12 col-xs-12 col-md-offset-1 col-md-12">

  <%= image_tag(@picture.asset.url(:large),
                alt: @picture.caption,
                class: 'img-polaroid') %>
<h3>
  <%= @picture.caption %>
</h3>

<p>
  <%= @picture.description %>
</p>

<%= link_to 'Edit', edit_album_picture_path(@album, @picture), class: 'btn btn-warning' %> |
<%= link_to 'Back', album_pictures_path, class: 'btn btn-default' %>
</div>